# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powernode
    username: root
    password: 123123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mappert???????
  type-aliases-package: com.itheima.springbootmybatis.pojo
  #config-Location:#??mybatis???????